# Generated by Django 3.0.4 on 2020-04-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20200402_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
