# Generated by Django 3.0.4 on 2020-04-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.ManyToManyField(to='query.Writer')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
